name: Deploy Node Backend

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Upload backend files to VPS
      - name: Deploy Backend via RSYNC
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr
          path: ./
          remote_path: /home/shivalikventures/shivalikbackend
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.VPS_KEY }}

      # Install packages & restart backend
      - name: Install & Restart Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /home/shivalikventures/shivalikbackend
            npm install --production
            npx pm2 restart backend || npx pm2 start server.js --name backend
            npx pm2 save --force
