name: Deploy Node Backend

on:
  push:
    branches:
      - main   # change to master if needed

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Upload backend files
      - name: Deploy Backend via RSYNC
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: ./     # folder containing server.js & package.json
          remote_path: /home/shivalikventures/nodebackend
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.VPS_KEY }}

      # Install dependencies and restart node app
      - name: Install & Restart Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /home/shivalikventures/nodebackend
            npm install --production
            touch tmp/restart.txt
